version: "3.8"

services:
  mysql_latest:
    platform: linux/amd64
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Tokyo
    volumes:
      - ./data/mysql/latest:/var/lib/mysql

  mysql_5_7_43:
    platform: linux/amd64
    image: mysql:5.7.43
    ports:
      - "5743:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: Asia/Tokyo
    volumes:
      - ./data/mysql/5.7.43:/var/lib/mysql
